
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true