version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/db

volumes:
  data-volume:
